language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - if [ "$TRAVIS_SOLO" != "true" ]; then COALRINGBUF_FULL_TEST=1; fi;
    nosetests -v --with-coverage --cover-package=coalringbuf
